// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPartners = `-- name: CountPartners :one
select count(*) from partners
`

func (q *Queries) CountPartners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPartners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedActivities = `-- name: CountPublishedActivities :one
select count(*) from activities where status = 'published'
`

func (q *Queries) CountPublishedActivities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedActivities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedEvents = `-- name: CountPublishedEvents :one
select count(*) from events where status = 'published'
`

func (q *Queries) CountPublishedEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPosts = `-- name: CountPublishedPosts :one
select count(*) from posts where status = 'published'
`

func (q *Queries) CountPublishedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPartners = `-- name: ListPartners :many
select id, name, logo_media_id, url, sort
from partners
order by sort asc, name asc
limit $1 offset $2
`

type ListPartnersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPartners(ctx context.Context, arg ListPartnersParams) ([]Partner, error) {
	rows, err := q.db.Query(ctx, listPartners, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partner
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoMediaID,
			&i.Url,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedActivities = `-- name: ListPublishedActivities :many
select id, name, category, image_media_id, sort
from activities
where status = 'published'
order by sort asc, name asc
limit $1 offset $2
`

type ListPublishedActivitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedActivitiesRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Category     string      `json:"category"`
	ImageMediaID pgtype.UUID `json:"image_media_id"`
	Sort         int32       `json:"sort"`
}

func (q *Queries) ListPublishedActivities(ctx context.Context, arg ListPublishedActivitiesParams) ([]ListPublishedActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedActivities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedActivitiesRow
	for rows.Next() {
		var i ListPublishedActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.ImageMediaID,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEvents = `-- name: ListPublishedEvents :many
select id, title, poster_media_id, starts_at, ends_at, sort
from events
where status = 'published'
order by starts_at desc nulls last, sort asc
limit $1 offset $2
`

type ListPublishedEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedEventsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	PosterMediaID pgtype.UUID        `json:"poster_media_id"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Sort          int32              `json:"sort"`
}

func (q *Queries) ListPublishedEvents(ctx context.Context, arg ListPublishedEventsParams) ([]ListPublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEventsRow
	for rows.Next() {
		var i ListPublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PosterMediaID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
select id, title, slug, cover_media_id, excerpt, published_at
from posts
where status = 'published'
order by published_at desc nulls last, created_at desc
limit $1 offset $2
`

type ListPublishedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedPostsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	CoverMediaID pgtype.UUID        `json:"cover_media_id"`
	Excerpt      string             `json:"excerpt"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPostsRow
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.CoverMediaID,
			&i.Excerpt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
