// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Category     string             `json:"category"`
	ImageMediaID pgtype.UUID        `json:"image_media_id"`
	Info         []byte             `json:"info"`
	Sort         int32              `json:"sort"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	PosterMediaID pgtype.UUID        `json:"poster_media_id"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Body          []byte             `json:"body"`
	Status        string             `json:"status"`
	Sort          int32              `json:"sort"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Medium struct {
	ID        pgtype.UUID        `json:"id"`
	Kind      string             `json:"kind"`
	Path      string             `json:"path"`
	Filename  string             `json:"filename"`
	Size      int64              `json:"size"`
	Width     *int32             `json:"width"`
	Height    *int32             `json:"height"`
	Alt       string             `json:"alt"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Menu struct {
	ID        pgtype.UUID        `json:"id"`
	Zone      string             `json:"zone"`
	Items     []byte             `json:"items"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Page struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Title     string             `json:"title"`
	Seo       []byte             `json:"seo"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Sort      int32              `json:"sort"`
	Status    string             `json:"status"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PageRevision struct {
	ID        pgtype.UUID        `json:"id"`
	PageID    pgtype.UUID        `json:"page_id"`
	Kind      string             `json:"kind"`
	Blocks    []byte             `json:"blocks"`
	Seo       []byte             `json:"seo"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Partner struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	LogoMediaID pgtype.UUID `json:"logo_media_id"`
	Url         *string     `json:"url"`
	Sort        int32       `json:"sort"`
}

type Post struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	CoverMediaID pgtype.UUID        `json:"cover_media_id"`
	Excerpt      string             `json:"excerpt"`
	Blocks       []byte             `json:"blocks"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	ID   pgtype.UUID `json:"id"`
	Data []byte      `json:"data"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DisabledAt   pgtype.Timestamptz `json:"disabled_at"`
}
