// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"
)

const getPublishedPageBySlug = `-- name: GetPublishedPageBySlug :one
select p.slug, p.title, p.seo, r.blocks
from pages p
join page_revisions r on r.page_id = p.id and r.kind = 'published'
where p.slug = $1 and p.deleted_at is null
`

type GetPublishedPageBySlugRow struct {
	Slug   string `json:"slug"`
	Title  string `json:"title"`
	Seo    []byte `json:"seo"`
	Blocks []byte `json:"blocks"`
}

func (q *Queries) GetPublishedPageBySlug(ctx context.Context, slug string) (GetPublishedPageBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPageBySlug, slug)
	var i GetPublishedPageBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Seo,
		&i.Blocks,
	)
	return i, err
}
