// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site.sql

package db

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
select data from settings limit 1
`

func (q *Queries) GetSettings(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const listMenus = `-- name: ListMenus :many
select zone, items from menus
`

type ListMenusRow struct {
	Zone  string `json:"zone"`
	Items []byte `json:"items"`
}

func (q *Queries) ListMenus(ctx context.Context) ([]ListMenusRow, error) {
	rows, err := q.db.Query(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenusRow
	for rows.Next() {
		var i ListMenusRow
		if err := rows.Scan(&i.Zone, &i.Items); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
